# Generated by Django 5.1.2 on 2024-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZApp', '0003_stickerdesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerdesign',
            name='user',
        ),
        migrations.AlterField(
            model_name='stickerdesign',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
